# Generated by Django 5.0.2 on 2024-03-22 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_archivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calificaciones_respuestas',
            },
        ),
        migrations.CreateModel(
            name='ActividadChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'actividad_chatbot',
            },
        ),
    ]
